version: '3.8'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tgcoinbackend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000/
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tgcoinbackend
      PORT: 3000
      TELEGRAM_WEB_APP_URL: https://your-web-app-url.com
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: nginx:stable-perl
    ports:
      - "80:80" # Доступ через порт 80
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge