FROM node:22.9-alpine AS build
WORKDIR /app
COPY ./client ./client
COPY server ./server
RUN cd ./client && npm ci
RUN cd ./server && npm ci
RUN cd ./client && npm run build

FROM nginx:stable-perl AS production

# Копируем собранное приложение в nginx
COPY --from=build /app/client/dist /usr/share/nginx/html

COPY client/nginx-frontend.conf /etc/nginx/conf.d/default.conf


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]